FROM python:3.13.7-slim

ENV PYTHONUNBUFFERED=True

WORKDIR /usr/src/app

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend ./

ENV PYTHONPATH=/usr/src/app

EXPOSE 4050

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4050"]


